OBJECTS = args.o args_parser.o collection.o conjugation.o definition.o def_term.o dictionary.o file.o init.o ords.o plaintext.o question.o settings.o ui.o uifuncs.o utils.o wrapper.o

ords: $(OBJECTS)
	g++ -o ords $(OBJECTS)

ords.o: ords.cpp file/file.h
	g++ -Wall -pedantic -c ords.cpp
	
file.o: file/file.cpp file/file.h
	g++ -Wall -pedantic -c file/file.cpp
	
plaintext.o: file/plaintext.cpp file/plaintext.h
	g++ -Wall -pedantic -c file/plaintext.cpp
	
settings.o: file/settings.cpp file/settings.h
	g++ -Wall -pedantic -c file/settings.cpp
	
args.o: cli/args.cpp cli/args.h
	g++ -Wall -pedantic -c cli/args.cpp
	
args_parser.o: cli/args_parser.cpp cli/args_parser.h
	g++ -Wall -pedantic -c cli/args_parser.cpp
	
ui.o: cli/ui.cpp cli/ui.h
	g++ -Wall -pedantic -c cli/ui.cpp
	
uifuncs.o: cli/uifuncs.cpp cli/uifuncs.h
	g++ -Wall -pedantic -c cli/uifuncs.cpp
	
init.o: init/init.cpp init/init.h
	g++ -Wall -pedantic -c init/init.cpp
	
definition.o: data/definition.cpp data/definition.h
	g++ -Wall -pedantic -c data/definition.cpp
	
def_term.o: data/def_term.cpp data/def_term.h
	g++ -Wall -pedantic -c data/def_term.cpp
	
wrapper.o: data/wrapper.cpp data/wrapper.h
	g++ -Wall -pedantic -c data/wrapper.cpp

question.o: data/question.cpp data/question.h
	g++ -Wall -pedantic -c data/question.cpp

conjugation.o: data/conjugation.cpp data/conjugation.h
	g++ -Wall -pedantic -c data/conjugation.cpp
	
dictionary.o: data/dictionary.cpp data/dictionary.h
	g++ -Wall -pedantic -c data/dictionary.cpp

collection.o: data/collection.cpp data/collection.h
	g++ -Wall -pedantic -c data/collection.cpp
	
utils.o: utils/utils.cpp utils/utils.h
	g++ -Wall -pedantic -c utils/utils.cpp

clean:
	rm ords $(OBJECTS)
